In [6]:
import tensorflow as tf
mat1 = tf.zeros([2,3])
mat2 = tf.ones([3,2])
mat3 = tf.fill([2,3],15)
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2 ))
    print(sess.run(mat3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [10]:
import tensorflow as tf
mat1 = tf.constant([[2],[3],[4]])
mat2 = tf.zeros_like(mat1) #tf.zeros_like(mat1)中的zeros说明是全0矩阵，like(mat1)意思是和mat1同一个维度结构
mat4 = tf.random_uniform([2,3],-1,2)  #2*3的数值在-1到2的矩阵
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[[ 0.4525292   1.5925994   1.8348002 ]
 [ 0.74712443  0.611763   -0.89171743]]
